apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hit-counter
  template:
    metadata:
      labels:
        app: hit-counter
    spec:
      containers:
      - name: hit-counter-app
        image: hit-counter-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: hit-counter
  ports:
  - port: 5000